'use strict'

module.exports = {
  WRONG_PASSWORD: 'WRONG_PASSWORD',
  INVALID_USERNAME: 'INVALID_USERNAME',
  PRODUCT_UNAVALIABLE: 'PRODUCT_UNAVALIABLE',
  USERNAME_IS_NOT_AVAILABLE: 'USERNAME_IS_NOT_AVAILABLE',
  NOT_FOUND: 'NOT_FOUND'
}
